
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../../../touch/src",
  "Ext.data.ProxyMgr": "../../../../touch/src/app/Application.js",
  "Ext.device.Purchases.Product": "../../../../touch/src/device/purchases/Sencha.js",
  "Ext.device.filesystem.DirectoryEntry": "../../../../touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.Entry": "../../../../touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.FileEntry": "../../../../touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.FileSystem": "../../../../touch/src/device/filesystem/HTML5.js",
  "Ext.device.purchases.Purchase": "../../../../touch/src/device/purchases/Sencha.js",
  "Ext.device.sqlite.Database": "../../../../touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLResultSet": "../../../../touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLResultSetRowList": "../../../../touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLTransaction": "../../../../touch/src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "../../../../touch/src/draw/engine/SvgContext.js",
  "Ext.grid": "../../src/grid",
  "Ext.grid.column.Action": "../../src/grid/column/unsupported/Action.js",
  "Ext.grid.column.CheckColumn": "../../src/grid/column/unsupported/CheckColumn.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.grid.Grid": [],
  "Ext.grid.HeaderContainer": [],
  "Ext.grid.HeaderGroup": [],
  "Ext.grid.Row": [],
  "Ext.grid.column.Action": [
    "Ext.grid.ActionColumn"
  ],
  "Ext.grid.column.Boolean": [],
  "Ext.grid.column.CheckColumn": [
    "Ext.ux.CheckColumn"
  ],
  "Ext.grid.column.Column": [],
  "Ext.grid.column.Date": [],
  "Ext.grid.column.Number": [],
  "Ext.grid.column.Template": [],
  "Ext.grid.infinite.Grid": [],
  "Ext.grid.infinite.Row": [],
  "Ext.grid.infinite.TemplateRow": [],
  "Ext.grid.plugin.ColumnResizing": [],
  "Ext.grid.plugin.Editable": [],
  "Ext.grid.plugin.MultiSelection": [],
  "Ext.grid.plugin.PagingToolbar": [],
  "Ext.grid.plugin.SummaryRow": [],
  "Ext.grid.plugin.ViewOptions": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.grid.Grid": [
    "widget.grid"
  ],
  "Ext.grid.HeaderContainer": [
    "widget.headercontainer"
  ],
  "Ext.grid.HeaderGroup": [
    "widget.gridheadergroup"
  ],
  "Ext.grid.Row": [
    "widget.gridrow"
  ],
  "Ext.grid.column.Action": [
    "widget.actioncolumn"
  ],
  "Ext.grid.column.Boolean": [
    "widget.booleancolumn"
  ],
  "Ext.grid.column.CheckColumn": [
    "widget.checkcolumn"
  ],
  "Ext.grid.column.Column": [
    "widget.column"
  ],
  "Ext.grid.column.Date": [
    "widget.datecolumn"
  ],
  "Ext.grid.column.Number": [
    "widget.numbercolumn"
  ],
  "Ext.grid.column.Template": [
    "widget.templatecolumn"
  ],
  "Ext.grid.infinite.Grid": [
    "widget.grid"
  ],
  "Ext.grid.infinite.Row": [
    "widget.gridrow"
  ],
  "Ext.grid.infinite.TemplateRow": [
    "widget.listgridrow"
  ],
  "Ext.grid.plugin.ColumnResizing": [
    "plugin.gridcolumnresizing"
  ],
  "Ext.grid.plugin.Editable": [
    "plugin.grideditable"
  ],
  "Ext.grid.plugin.MultiSelection": [
    "plugin.gridmultiselection"
  ],
  "Ext.grid.plugin.PagingToolbar": [
    "plugin.gridpagingtoolbar"
  ],
  "Ext.grid.plugin.SummaryRow": [
    "plugin.gridsummaryrow"
  ],
  "Ext.grid.plugin.ViewOptions": [
    "plugin.gridviewoptions"
  ]
});
