
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../touch/src",
  "Ext-more": "../../touch/src/core/Ext-more.js",
  "Ext.DomHelper": "../../touch/src/dom/Helper.js",
  "Ext.DomQuery": "../../touch/src/dom/Query.js",
  "Ext.Element-alignment": "../../touch/src/dom/Element.alignment.js",
  "Ext.Element-all": "../../touch/src/dom/Element.traversal.js",
  "Ext.Element-insertion": "../../touch/src/dom/Element.insertion.js",
  "Ext.Element-position": "../../touch/src/dom/Element.position.js",
  "Ext.Element-static": "../../touch/src/dom/Element.static.js",
  "Ext.Element-style": "../../touch/src/dom/Element.style.js",
  "Ext.Element-traversal": "../../touch/src/dom/Element.traversal.js",
  "Ext.core.DomQuery": "../../touch/src/dom/Query.js",
  "Ext.device.Purchases.Product": "../../touch/src/device/purchases/Sencha.js",
  "Ext.device.filesystem.DirectoryEntry": "../../touch/src/device/filesystem/Sencha.js",
  "Ext.device.filesystem.Entry": "../../touch/src/device/filesystem/Sencha.js",
  "Ext.device.filesystem.FileEntry": "../../touch/src/device/filesystem/Sencha.js",
  "Ext.device.filesystem.FileSystem": "../../touch/src/device/filesystem/Sencha.js",
  "Ext.device.purchases.Purchase": "../../touch/src/device/purchases/Sencha.js",
  "Ext.device.sqlite.Database": "../../touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLResultSet": "../../touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLResultSetRowList": "../../touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLTransaction": "../../touch/src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "../../touch/src/draw/engine/SvgContext.js",
  "FindACab": "app",
  "Utils": "utils"
});
Ext.ClassManager.addNameAlternateMappings({
  "FindACab.controller.CabController": [],
  "FindACab.controller.SettingsController": [],
  "FindACab.model.Cab": [],
  "FindACab.model.Setting": [],
  "FindACab.store.Cabs": [],
  "FindACab.store.Settings": [],
  "FindACab.view.DetailView": [],
  "FindACab.view.Main": [],
  "FindACab.view.Overview": [],
  "FindACab.view.RatingChart": [],
  "FindACab.view.SettingsView": [],
  "Utils.Commons": []
});
Ext.ClassManager.addNameAliasMappings({
  "FindACab.controller.CabController": [],
  "FindACab.controller.SettingsController": [],
  "FindACab.model.Cab": [],
  "FindACab.model.Setting": [],
  "FindACab.store.Cabs": [],
  "FindACab.store.Settings": [],
  "FindACab.view.DetailView": [
    "widget.detailview"
  ],
  "FindACab.view.Main": [],
  "FindACab.view.Overview": [
    "widget.overview"
  ],
  "FindACab.view.RatingChart": [
    "widget.ratingchart"
  ],
  "FindACab.view.SettingsView": [
    "widget.settingsview"
  ],
  "Utils.Commons": []
});
